#!/usr/bin/env bash
# Builds the recording workspace: the Harbor checkout, the PATH shim that puts
# the scripted agent where Wake looks for `claude`, and a scratch socket.
#
# Everything it makes lives under demo/.work, which is ignored. Re-runnable.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
work="$here/.work"

# Takes are expensive — a full set is ~25 minutes of recording — so re-running
# setup must never destroy them. Everything below is rebuilt; out/ and cards/
# are left exactly where they are.
rm -rf "$work/bin" "$work/harbor" "$work/claudehome" "$work/seg"
mkdir -p "$work/bin" "$work/out" "$work/cards"

# The fictional product, as a real git repository — the conversation status bar
# reads a real branch through internal/gitref, so a drawn one would be a lie on
# camera.
cp -R "$here/harbor" "$work/harbor"
git -C "$work/harbor" init --quiet --initial-branch=main
git -C "$work/harbor" -c user.email=dev@harbor.dev -c user.name=Harbor \
    add -A
git -C "$work/harbor" -c user.email=dev@harbor.dev -c user.name=Harbor \
    commit --quiet -m "harbor 0.4.0"
git -C "$work/harbor" checkout --quiet -b feat/rate-limit

# What Wake spawns. internal/core resolves `claude` on PATH and nothing else,
# so a shim directory in front of PATH is the whole substitution.
ln -sf "$here/agent/claude" "$work/bin/claude"

# The real binary, built from this worktree.
( cd "$root" && go build -o "$work/bin/wake" ./cmd/wake )

# A scratch HOME for the whole recording. Wake reads conversations back from
# $HOME/.claude/projects, so this both gives the fake somewhere to journal and
# guarantees nothing of the operator's real Claude data can reach the camera.
#
# Named `claudehome` rather than `home` because internal/core's corpus guard
# matches a unix home path with an owner attached, tree-wide, to catch a leaked
# home directory — and the shorter name trips it on the `.claude` beneath.
mkdir -p "$work/claudehome/.claude/projects/harbor"

cat > "$work/env.sh" <<EOF
# source this to record
export PATH="$work/bin:\$PATH"
export HOME="$work/claudehome"
export WAKE_SOCKET="$work/wake.sock"
export WAKE_DEMO_SCENARIOS="$here/scenarios"
export HARBOR="$work/harbor"
export PS1="%F{244}harbor%f %F{209}\$%f "
EOF

# The staging tape is generated rather than written, because `/new <name> in
# <dir>` resolves a relative directory against the *session's* directory, not
# the shell's — so `in web` from an agent started in api/ means api/web, which
# does not exist, and a refused command keeps its draft for the next line to
# concatenate onto. Absolute paths remove the question.
cat > "$work/stage.tape" <<EOF
# GENERATED by demo/setup.sh — edit setup.sh, not this file.
#
# The fleet every beat is filmed against. Sourced, never recorded: each beat
# tape wraps it in Hide and calls Show once the room is ready.
#
# \`wake new maya\` rather than a bare \`wake\`, because a bare one spawns an
# agent from the name pool when it finds nothing running — which would put a
# different random name in the cast on every take.

Set TypingSpeed 8ms

Type "source ./.work/env.sh && wake stop >/dev/null 2>&1 && sleep 1 && cd \$HARBOR/api && clear"
Enter
Sleep 4s

Type "wake new maya"
Enter
Sleep 7s

# Close maya's pane, so staging happens against the room alone.
Ctrl+W
Sleep 2s

Type "/new omar in $work/harbor/web"
Enter
Sleep 6s
Type "/new priya in $work/harbor/cli"
Enter
Sleep 6s
Type "/new luca in $work/harbor/docs"
Enter
Sleep 6s
Type "/new nora in $work/harbor/api"
Enter
Sleep 6s
Type "/new alex in $work/harbor/api"
Enter
Sleep 5s

# \`/new\` opens the conversation it started and gives it the keys, so the last
# one leaves the room unfocused — and every line typed after it would go to
# that agent's DM instead of the group chat. Closing it hands the keys back.
Ctrl+W
Sleep 2s

# Labels are what a fleet is triaged by: they head every line an agent says,
# fill the roster and the board, and are the only handle the manager has for
# "the agents working on the api".
Type "/task @maya api · token-bucket middleware"
Enter
Sleep 3s
Type "/task @omar web · 429 client state"
Enter
Sleep 3s
Type "/task @priya cli · --rate-limit flag"
Enter
Sleep 3s
Type "/task @luca docs · changelog and limits page"
Enter
Sleep 3s
Type "/task @nora api · limiter tests"
Enter
Sleep 3s
Type "/task @alex api · limiter benchmarks"
Enter
Sleep 4s

Set TypingSpeed 55ms
EOF

# Recording settings shared by every beat tape. Generated here so a re-run of
# setup cannot leave the tapes pointing at a file that no longer exists.
cat > "$work/head.tape" <<'EOT'
# GENERATED by demo/setup.sh — edit setup.sh, not this file.
Set Shell zsh
Set FontSize 16
Set Width 2400
Set Height 1320
Set Padding 24
Set WindowBar Colorful
EOT

echo "workspace ready: $work"
echo "  harbor  $(git -C "$work/harbor" branch --show-current)"
echo "  claude  $(readlink "$work/bin/claude")"
echo "  wake    $("$work/bin/wake" --version 2>/dev/null || echo built)"
